### PR TITLE
detect and switch qt versions with autotools

### PR DESCRIPTION
**Pull request by dmio**
This should be more compatible with different distros.

### CODE REVIEW

**Comment by netblue30** [comment]
Merged, thanks!

**Comment by netblue30** [comment]
I had to revert the merge for now. On Debian wheezy once you install qtchooser, libqt4-dev is uninstalled. If you install libqt4-dev, qtchooser package is removed from the system.

```
$ sudo apt-get install qtchooser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libavahi-core7 libdaemon0 libgconfmm-2.6-1c2 libgl1-mesa-dev
  libglu1-mesa-dev libmysqlclient18 libpthread-stubs0 libpthread-stubs0-dev
  libqt4-declarative libqt4-designer libqt4-help libqt4-opengl
  libqt4-qt3support libqt4-script libqt4-scripttools libqt4-sql
  libqt4-sql-mysql libqt4-svg libqt4-test libqt4-xmlpatterns libqtwebkit4
  libx11-dev libx11-doc libxau-dev libxcb1-dev libxdmcp-dev libxext-dev
  mesa-common-dev mysql-common pulseaudio-module-gconf x11proto-core-dev
  x11proto-input-dev x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
Use 'apt-get autoremove' to remove them.
Suggested packages:
  qt4-default qt5-default
The following packages will be REMOVED:
  libqt4-dbus libqt4-dev libqt4-dev-bin libqt4-opengl-dev libqtwebkit-dev
  qdbus qt4-linguist-tools qt4-qmake
The following NEW packages will be installed:
  qtchooser
0 upgraded, 1 newly installed, 8 to remove and 0 not upgraded.
```

I'll try to find a way around it.

**Comment by dmio** [comment]
I tested it on debian wheezy and jessie. It's ok with jessie. But it seems there is a bug with wheezy-backports.

**Comment by dmio** [comment]
As I understand, you can't reopen merged pull request.
So, take a look at this patch.
https://github.com/dmio/firetools/commit/5ee0377fd11d4b842d016ebff95912040b133179

**Comment by netblue30** [comment]
Sure, I'll give it a try, thanks!

**Pull request merged**
